# extend pyproject.toml for requires-python (workaround astral-sh/ruff#10299)
extend = "pyproject.toml"

[lint]
extend-select = [
	"C901",
	"PERF401",
	"W",

	# local
	"B",
	"I",
	"ISC",
	"PERF",
	"RUF010",
	"RUF100",
	"TRY",
	"UP",
	"YTT",
]
ignore = [
	# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
	"W191",
	"E111",
	"E114",
	"E117",
	"D206",
	"D300",
	"Q000",
	"Q001",
	"Q002",
	"Q003",
	"COM812",
	"COM819",
	"ISC001",
	"ISC002",

	# local
	"B028",
	"B904",
	"PERF203",
	"TRY003",
	"TRY400",
]

[format]
# Enable preview to get hugged parenthesis unwrapping and other nice surprises
# See https://github.com/jaraco/skeleton/pull/133#issuecomment-2239538373
preview = true
# https://docs.astral.sh/ruff/settings/#format_quote-style
quote-style = "preserve"
